Repository openedx/xblock-sdk, pull requests merged in 2019-02, with the labels that each got.

#146 make upgrade
  .travis.yml
  requirements/base.txt
  requirements/dev.txt
  requirements/quality.txt
  requirements/test.txt
  requirements/travis.txt
  sample_xblocks/basic/content.py
  sample_xblocks/basic/problem.py
  sample_xblocks/basic/slider.py
  sample_xblocks/basic/structure.py
  setup.py
  tox.ini
  workbench/blocks.py
  workbench/runtime.py
  workbench/scenarios.py
  workbench/test/test_problems.py
  workbench/test/test_runtime.py
  workbench/test/test_scenarios.py
  workbench/test/test_views.py
  workbench/test_utils.py
  workbench/views.py
Labels: open-source-contribution, waiting on author

#144 [INCR 75] only require futures for python 2.7
  constraints.txt
  requirements/base.in
  requirements/base.txt
  requirements/dev.txt
  requirements/quality.in
  requirements/quality.txt
  requirements/test.in
  requirements/test.txt
  requirements/travis.in
  requirements/travis.txt
Labels: blocked by other work, open-source-contribution

#145 [INCR 77] test with python 3.6/3.7 & django 2.0/2.1
  .travis.yml
  setup.py
  tox.ini
Labels: open-source-contribution, waiting on author

#147 [INCR-98] and [INCR-99] Run Python modernize -w .
  .travis.yml
  bin/workbench-make-xblock
  doc/conf.py
  manage.py
  prototype/{{cookiecutter.short_name}}/setup.py
  prototype/{{cookiecutter.short_name}}/{{cookiecutter.short_name}}/{{cookiecutter.short_name}}.py
  requirements/dev.txt
  requirements/quality.txt
  sample_xblocks/basic/content.py
  sample_xblocks/basic/problem.py
  sample_xblocks/basic/slider.py
  sample_xblocks/basic/structure.py
  sample_xblocks/basic/test/test_problem.py
  sample_xblocks/basic/test/test_view_counter.py
  sample_xblocks/basic/view_counter.py
  sample_xblocks/filethumbs/filethumbs.py
  sample_xblocks/thumbs/thumbs.py
  settings.py
  setup.py
  tox.ini
  workbench/admin.py
  workbench/blocks.py
  workbench/migrations/0001_initial.py
  workbench/models.py
  workbench/runtime.py
  workbench/scenarios.py
  workbench/settings.py
  workbench/test/selenium_test.py
  workbench/test/test_filethumbs.py
  workbench/test/test_problems.py
  workbench/test/test_runtime.py
  workbench/test/test_scenarios.py
  workbench/test/test_thumbs.py
  workbench/test/test_views.py
  workbench/test_utils.py
  workbench/urls.py
  workbench/views.py
  workbench/wsgi.py
Labels: engineering review, open-source-contribution
